name: 🚀 Deploy to Ferozo

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Update DB credentials in src/index.php
        run: |
          sed -i "s/'username' => 'php-crud-api'/'username' => '${{ secrets.DB_USERNAME }}'/g" src/index.php
          sed -i "s/'password' => 'php-crud-api'/'password' => '${{ secrets.DB_PASSWORD }}'/g" src/index.php
          sed -i "s/'database' => 'php-crud-api'/'database' => '${{ secrets.DB_NAME }}'/g" src/index.php

      - name: Install FTP client
        run: sudo apt-get install -y lftp

      - name: Upload selected files via FTP
        env:
          FTP_SERVER: ${{ secrets.FEROZO_USER }}.ferozo.com
          FTP_USERNAME: ${{ secrets.FEROZO_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          run: lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -e "mirror -R --delete --verbose --parallel=20 --exclude-glob .git/ src /public_html/${PROJECT_NAME}/src; mirror -R --delete --verbose --parallel=20 vendor /public_html/${PROJECT_NAME}/vendor; put src/index.php -o /public_html/${PROJECT_NAME}/index.php; bye" ftp://$FTP_SERVER || true
